# Graphs

### Working with Graphs
- Graphs are an essential data structure.
- SciPy provides us with the module `scipy.sparse.csgraph` for working with such data structures.
### Adjacency Matrix
- Adjacency matrix is a nxn matrix where n is the number of elements in a graph.
- And the values represents the connection between the elements.

![My chart](./scipy_graph.png)



- For a graph like this, with elements A, B and C, the connections are:
- A & B are connected with weight 1.
- A & C are connected with weight 2.
- C & B is not connected.
- The Adjency Matrix would look like this:
### Connected Components
- Find all of the connected components with the connected_components() method

In [37]:
import numpy as np
from scipy.sparse.csgraph import connected_components, dijkstra, floyd_warshall, bellman_ford, depth_first_order, breadth_first_order
from scipy.sparse import csr_matrix

In [38]:
arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


### Dijkstra
- Use the `dijkstra` method to find the shortest path in a graph from one element to another.
- It takes following arguments:
- return_predecessors: boolean (True to return whole path of traversal otherwise False).
- indices: index of the element to return all paths from that element only.
- limit: max weight of path.

In [39]:
arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])
newarr = csr_matrix(arr)
print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


### Floyd Warshall
- Use the `floyd_warshall()` method to find shortest path between all pairs of elements.

In [40]:
arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])
newarr = csr_matrix(arr)
print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


### Bellman Ford
- The `bellman_ford()` method can also find the shortest path between all pairs of elements, but this method can handle negative weights as well.

In [41]:
arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])
newarr = csr_matrix(arr)
print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))


### Depth First Order
- The `depth_first_order()` method returns a depth first traversal from a node.
This function takes following arguments:
1. the graph.
2. the starting element to traverse graph from.

In [42]:
arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])
newarr = csr_matrix(arr)
print(depth_first_order(newarr, 1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


### Breadth First Order
- The `breadth_first_order()` method returns a breadth first traversal from a node.
- This function takes following arguments:
1. the graph.
2. the starting element to traverse graph from.

In [44]:
# Make sure cell 4 has been run so breadth_first_order is available
print(breadth_first_order(newarr, 1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))
