# Numpy

In [1]:
# import numpy
import numpy as np

Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of the same type of data.

- Once created, the total size of the array can’t change.

- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [8]:
# initialize array
a = np.array([1,2,3,4,5,6,7])
print(a, type(a), a.shape)
print("------")
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b, type(b), b.shape)

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> (7,)
------
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [ ]:
# accessing te element
print(a[1]) # output: 2
print(b[1,2]) #output: 6

# replace element
a[3] = 44
print(a)

# indexing
print(a[3:6])
print(b[0:2, 2])


2
6
[ 1  2  3 44  5  6  7]
[44  5  6]
[[3]
 [6]]


In [16]:
# nested array ceated as this
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a, type(a), a.shape)
print(a[1,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'> (3, 4)
8


# Array attributes

In [23]:
# number of dimensions
print(a.ndim)
print(b.ndim)
# shape of arrays
print(a.shape)
print(b.shape)
len(a.shape)  == a.ndim  # output : True
# total number of elements
print(a.size)
print(b.size)
import math
a.size == math.prod(a.shape)  # output : True
# data type
print(a.dtype)
print(b.dtype)

2
2
(3, 4)
(2, 3)
12
6
int64
int64


# Create a basic array

In [36]:
# create zeros elements array
print(np.zeros(2))
print(np.zeros((1,1)))
print(np.zeros((3,4), dtype=np.int64))
# create once elements array
print(np.ones(2))
print(np.ones((1,1)))
print(np.ones((3,4), dtype=np.int64))
# create empty elements array
print("--------")
print(np.empty(2))
print(np.empty((1,1)))
print(np.empty((3,4), dtype=np.int64))
print("--------")
# create array with arange
print(np.arange(5))
print(np.arange(3, 7))
print(np.arange(3, 10, 2))
print("---------")
# create array with linear space
print(np.linspace(0, 10, num=5))

[0. 0.]
[[0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1. 1.]
[[1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
--------
[1. 1.]
[[1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
--------
[0 1 2 3 4]
[3 4 5 6]
[3 5 7 9]
---------
[ 0.   2.5  5.   7.5 10. ]
